name: Hello Triggered Workflow
on:
  repository_dispatch:
    types: [hello_event]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ github.event.client_payload.name }}!"
