name: Trigger Hello Workflow
on:
  push:
    branches:
      - main # Adjust branch name as needed

jobs:
  trigger_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hello Workflow in z-auth/ci
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/z-auth/ci/actions/workflows/:workflow_id/dispatches
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow_id: "hello-triggered.yml"
          client_payload: '{"name": "Trigger"}' # Example payload; replace with your inputs
          inputs: |
            ref: ${{ github.ref }}
